---
version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.16
    parallelism: 1
    steps:
      - checkout
      - run: env CGO_ENABLED=0 go vet ./...
      - run: env CGO_ENABLED=0 go build -a
      - run: env CGO_ENABLED=0 GOOS=windows go build -a
      - run: env CGO_ENABLED=0 GOARCH=arm go build -a
      - run: env CGO_ENABLED=0 go test -count=1 -v -cover ./...
